version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.3.0
    working_directory: ~/project
    steps:
      - checkout
      - run: node -v
      - run:
          name: Show current branch
          command: echo ${CURRENT_BRANCH}
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  deploy-to-s3:
    docker:
      - image: cimg/node:16.3.0
    working_directory: ~/project
    steps:
      - checkout
      - run: node -v
      - run:
          name: Show current branch
          command: echo ${CURRENT_BRANCH}
      - run:
          name: Installing AWS CLI
          working_directory: /
          command: |
            sudo apt-get-y -qq update
            sudo apt-get install -y awscli
      - run:
          name: Build Project
          command: |
            yarn install
            yarn build
            cd build
            zip ../build.zip -r * .[^.]*
            echo "Build completed"
      - run:
          name: Deploy to AWS S3
          command: |
            if [ "${CURRENT_BRANCH}" == "production"]
            then 
              aws --region ${AWS_REGION} s3 sync ~/project/build s3://${AWS_BUCKET_PRODUCTION} --delete
            elif [ "${CURRENT_BRANCH}" == "staging"]
            then 
              aws --region ${AWS_REGION} s3 sync ~/project/build s3://${AWS_BUCKET_STAGING} --delete
            else 
              aws --region ${AWS_REGION} s3 sync ~/project/build s3://${AWS_BUCKET_DEVELOPMENT} --delete
            fi

  deploy-to-cloudfront:
    docker:
      - image: cimg/node:16.3.0
    working_directory: ~/project
    steps:
      - checkout
      - run: node -v
      - run:
          name: Show current branch
          command: echo ${CURRENT_BRANCH}
      - run:
          name: Installing AWS CLI
          working_directory: /
          command: |
            sudo apt-get-y -qq update
            sudo apt-get install -y awscli
      - run:
          name: Build Project
          command: |
            yarn install
            yarn build
            cd build
            zip ../build.zip -r * .[^.]*
            echo "Build completed"
      - run:
          name: Deploy to AWS CloudFront
          command: |
            aws configure set preview.cloudfront
            if [ "${CURRENT_BRANCH}" == "production"]
            then 
              aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID_PRODUCTION} --paths /\*
            elif [ "${CURRENT_BRANCH}" == "staging"]
            then 
              aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID_STAGING} --paths /\*
            else 
              aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID_DEVELOPMENT} --paths /\*
            fi

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy-to-s3:
          requires:
            - build
          filters:
            branches:
              only:
                - development
                - staging
                - production
      - deploy-to-cloudfront:
          requires:
            - deploy-to-s3
          filters:
            branches:
              only:
                - development
                - staging
                - production
